spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dolphin?useSSL=false
    username: dolphin
    password: dolphinX2018
    initialization-mode: never
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          enable: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
          fallback: false

security:
  oauth2:
    client:
      authenticationScheme: header

logging:
  level:
    org.springframework.security: DEBUG
  file: logs/application.log

server:
  port: 8088
  error:
    whitelabel:
      enabled: false

oauth2:
  paths:
    token: /v1/oauth2/token
    check_token: /v1/oauth2/check_token
    token_key: /v1/oauth2/token_key
    authorize: /v1/oauth2/authorize
    confirm_access: /v1/oauth2/confirm_access
  keystore_file_uri: key/mykey.jks
  keystore_password: $ampl3
  keystore_alias: mykey
  custom_token_field_name: custom_field
  access_token_validity_seconds: 864000
  refresh_token_validity_seconds: 864000
  reuse_refresh_token: true
  resourceId: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

policy:
  json:
    filePath: policy/default-policy.json

facebook:
  appId: 2077266045922491
  appSecret: 956b865612495680eb4e8b0df1b92655
  scope: public_profile,email
  token_link: https://graph.facebook.com/oauth/access_token?client_id=%s&client_secret=%s&redirect_uri=%s&code=%s

---

spring:
  profiles: dev
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    initialization-mode: never
  zipkin:
    base-url: http://zipkin-server:9411/

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

oauth2:
  access_token_validity_seconds: 600
  refresh_token_validity_seconds: 86400

---

spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-server:9411/

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

oauth2:
  access_token_validity_seconds: 600
  refresh_token_validity_seconds: 86400

---
spring:
  profiles: test
  datasource:
    url: jdbc:mariadb://localhost:3306/dolphin-test?useSSL=false
    username: dolphin
    password: dolphinX2018
  liquibase:
    enabled: false