spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:mariadb://localhost:3306/data-db-test?useSSL=false
    username: dolphin
    password: dolphinX2018