spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mariadb://localhost:3306/data-db?useSSL=false
    username: dolphin
    password: dolphinX2018
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 60m
      use-key-prefix: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 500ms
      shutdown-timeout: 200ms

logging:
  level:
    org.springframework.security: DEBUG
  file: logs/application.log

server:
  port: 8082
  error:
    whitelabel:
      enabled: false
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: edium@123
    keyStoreType: PKCS12
    keyAlias: edium
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: ALWAYS

oauth2:
  resourceId: data-service
  paths:
    resource_file_uri: key/jwt_oauth2_key.pub

policy:
  json:
    filePath: policy/default-policy.json
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mariadb://mariadb:3306/data-db?useSSL=false
    username: dolphin
    password: dolphinX2018
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  zipkin:
    base-url: http://zipkin-server:9411/

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

---
spring:
  profiles: test
  datasource:
    url: jdbc:mariadb://localhost:3306/data-db-test?useSSL=false
    username: dolphin
    password: dolphinX2018