spring:
  application:
    name: core-service
  datasource:
    url: jdbc:mariadb://localhost:3306/dolphin?useSSL=false
    username: dolphin
    password: dolphinX2018
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    org.springframework.security: DEBUG
  file: logs/application.log

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

oauth2:
  resourceId: core-service
  paths:
    resource_file_uri: key/jwt_oauth2_key.pub

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mariadb://mariadb:3306/dolphin?useSSL=false
    username: dolphin
    password: dolphinX2018
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  zipkin:
    base-url: http://zipkin-server:9411/

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  zipkin:
    base-url: http://zipkin-server:9411/

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/